//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long employeeId { get; set; }
        public string employeeName { get; set; }
        public string employeeFName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<long> subjectId { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual User User { get; set; }
    }
}
