//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.UserRolePrivileges = new HashSet<UserRolePrivilege>();
        }
    
        public int roleId { get; set; }
        public int mainRoleId { get; set; }
        public string roleTitle { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public long modifiedBy { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRolePrivilege> UserRolePrivileges { get; set; }
    }
}
