//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.studentAppearTests = new HashSet<studentAppearTest>();
            this.studentRegisterForTests = new HashSet<studentRegisterForTest>();
        }
    
        public long studentId { get; set; }
        public string studentName { get; set; }
        public string studentFName { get; set; }
        public Nullable<byte> gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string studentPicture { get; set; }
        public string universityName { get; set; }
        public string departmentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentAppearTest> studentAppearTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentRegisterForTest> studentRegisterForTests { get; set; }
    }
}
