//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppLlicense
    {
        public long licenseId { get; set; }
        public Nullable<System.DateTime> dateTimeInitiated { get; set; }
        public Nullable<System.DateTime> uptoDate { get; set; }
        public Nullable<System.TimeSpan> timeStampPrevious { get; set; }
        public Nullable<System.DateTime> dateStampPrevious { get; set; }
        public Nullable<int> timeSpan { get; set; }
        public string machineKey { get; set; }
        public Nullable<int> numberOfRecords { get; set; }
        public Nullable<int> transectionsCount { get; set; }
        public Nullable<int> numberOfStudent { get; set; }
        public Nullable<System.DateTime> dateTimeLicenseExpire { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string licenseKey { get; set; }
        public Nullable<int> gracePeriod { get; set; }
        public Nullable<System.DateTime> gracePeriodStart { get; set; }
        public Nullable<System.DateTime> gracePeriofEnd { get; set; }
    }
}
