//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nMDCATPrepTestEntities : DbContext
    {
        public nMDCATPrepTestEntities()
            : base("name=nMDCATPrepTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classDomain> classDomains { get; set; }
        public virtual DbSet<departmentRanking> departmentRankings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<questionTypeDomain> questionTypeDomains { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentAppearTest> studentAppearTests { get; set; }
        public virtual DbSet<studentRegisterForTest> studentRegisterForTests { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAppLlicense> tblAppLlicenses { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<testQuestion> testQuestions { get; set; }
        public virtual DbSet<testQuestionDatabank> testQuestionDatabanks { get; set; }
        public virtual DbSet<universityRanking> universityRankings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<userPower> userPowers { get; set; }
        public virtual DbSet<UserRolePrivilege> UserRolePrivileges { get; set; }
    }
}
