//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public test()
        {
            this.studentAppearTests = new HashSet<studentAppearTest>();
            this.studentRegisterForTests = new HashSet<studentRegisterForTest>();
            this.testQuestions = new HashSet<testQuestion>();
        }
    
        public long testId { get; set; }
        public string testTitle { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public Nullable<int> graceTime { get; set; }
        public Nullable<System.DateTime> testConductionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentAppearTest> studentAppearTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentRegisterForTest> studentRegisterForTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testQuestion> testQuestions { get; set; }
    }
}
