//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class testQuestionDatabank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public testQuestionDatabank()
        {
            this.studentAppearTests = new HashSet<studentAppearTest>();
            this.testQuestions = new HashSet<testQuestion>();
        }
    
        public long questionId { get; set; }
        public string questionTitle { get; set; }
        public string choiceA { get; set; }
        public string choiceB { get; set; }
        public string choiceC { get; set; }
        public string choiceD { get; set; }
        public Nullable<long> subjectId { get; set; }
        public Nullable<long> questionClassId { get; set; }
        public string correctChoice { get; set; }
        public string description { get; set; }
        public Nullable<int> chapter { get; set; }
        public Nullable<int> qType { get; set; }
        public string correctChoiceForAll { get; set; }
    
        public virtual classDomain classDomain { get; set; }
        public virtual classDomain classDomain1 { get; set; }
        public virtual questionTypeDomain questionTypeDomain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentAppearTest> studentAppearTests { get; set; }
        public virtual subject subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testQuestion> testQuestions { get; set; }
    }
}
