//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPower
    {
        public long userPowerId { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<bool> isPowerful { get; set; }
    
        public virtual User User { get; set; }
    }
}
