//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMDCATEtestPreparatory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolePrivilege
    {
        public long upvId { get; set; }
        public int roleId { get; set; }
        public int privilegeId { get; set; }
        public long userId { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public long modifiedBy { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
    
        public virtual Privilege Privilege { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
